site_name: Klix Developers
site_description: Klix Developer documentation
site_author: Klix Development Team
theme:
  name: 'material'
  custom_dir: 'theme/'
  palette:
    primary: 'klix-theme-primary'
    accent: 'klix-theme-accent'
  logo: 'images/logos/klix_white.png'
  favicon: 'images/logos/favicon.png'
  features:
    - content.tabs.link
google_analytics:
  - 'UA-149580135-1'
  - 'auto'

# Plugins  
plugins:
  - search

 # Extensions
markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - toc:
      permalink: true
  - pymdownx.caret
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tilde

# Page tree
nav:
  - Overview: index.md
  - Test environment: test-environment.md
  - Plugins for eCommerce platforms: plugins-for-ecommerce-platforms.md
  - Libraries: libraries.md
  - Direct integration using API: api.md
  - Legacy Klix API (deprecated): widget-api.md
  - Static assets: static-assets.md

# Social
extra:
  social:
    - type: 'github'
      link: 'https://github.com/klix-app'
    - type: 'twitter'
      link: 'https://twitter.com/klixapp'
    - type: 'linkedin'
      link: 'https://lv.linkedin.com/company/klixapp'

# Style adjustments
extra_css:
  - 'stylesheets/klix.css'

# Repository
repo_name: klix-app/klix-developer-documentation-website
repo_url: https://github.com/klix-app/klix-developer-documentation-website
edit_uri: ""

# Copyright
copyright: 'Copyright &copy; 2021 Klix'

      