site_name: Klix Developers
site_description: Klix Developer documentation
site_author: Klix Development Team
theme:
  name: 'material'
  custom_dir: 'theme/'
  palette:
    primary: 'klix-theme-primary'
    accent: 'klix-theme-accent'
  logo: 'images/logos/klix_white.png'
  favicon: 'images/logos/favicon.png'
  features:
    - content.code.copy
    - navigation.footer
google_analytics:
  - 'UA-149580135-1'
  - 'auto'

# Plugins  
plugins:
  - search
#  - with-pdf:
#      cover_subtitle: Latest version of this documentation is available at developers.klix.app
#      cover_logo: docs/images/logos/klix_logo.png
#      back_cover: true
#      toc_level: 3
#      render_js: false
#      output_path: ../document.pdf

 # Extensions
markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - toc:
      permalink: true
  - pymdownx.caret
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tilde

# Page tree
nav:
  - Overview: index.md
  - Test environment: test-environment.md
  - Plugins for eCommerce platforms: plugins-for-ecommerce-platforms.md
  - Libraries: libraries.md
  - Direct integration using API: api.md
  - Static assets: static-assets.md
  - Representation guidelines: representation-guidelines.md
  - Marketing guidelines: marketing-guidelines.md

# Social
extra:
  social:
    - icon: fontawesome/brands/github
      link: 'https://github.com/klix-app'
    - icon: fontawesome/brands/twitter
      link: 'https://twitter.com/klixapp'
    - icon: fontawesome/brands/linkedin
      link: 'https://lv.linkedin.com/company/klixapp'

# Style adjustments
extra_css:
  - 'stylesheets/klix.css'

# Repository
repo_name: klix-app/klix-developer-documentation-website
repo_url: https://github.com/klix-app/klix-developer-documentation-website
edit_uri: ""

# Copyright
copyright: 'Copyright &copy; 2021-2023 Klix'

      